all : reverser-pointer reverser
reverser-pointer:reverser-pointer.c
	gcc reverser-pointer.c -o reverser-pointer

reverser:reverser.c
	gcc reverser.c -o reverser

clean:
	rm -rf reverser-pointer reverser

